### PR TITLE
Migrate custom nodes

### PR DESCRIPTION
**Pull request by pythongosssss**
Adds custom node migration using manager snapshots

┆Issue is synchronized with this [Notion page](https://www.notion.so/Issue-1968-Migrate-custom-nodes-15f6d73d3650815380fdfbd561e25820) by [Unito](https://www.unito.io)

### CODE REVIEW

**Comment by pythongosssss** [comment]
I don't think that is a very good method as:
1. at some point I want to remove my old manual installation and just have the desktop, where I would then need to manually reinstall them all
2. if I update custom nodes in one place, that will install the dependencies in one env, I then swap to the other installation and the custom nodes no longer work as I didn't update the nodes here, in this so new deps weren't installed

I think having the same source for custom nodes between two different environments, with different comfy versions, packages, etc will cause more trouble than it is worth

**Comment by huchenlei** [comment]
> I don't think that is a very good method as:
> 
> 1. at some point I want to remove my old manual installation and just have the desktop, where I would then need to manually reinstall them all
> 2. if I update custom nodes in one place, that will install the dependencies in one env, I then swap to the other installation and the custom nodes no longer work as I didn't update the nodes here, in this so new deps weren't installed
> 
> I think having the same source for custom nodes between two different environments, with different comfy versions, packages, etc will cause more trouble than it is worth

How about we directly copy the migration source's `custom_nodes` folder? This would help preserving data some custom nodes saved in their own folder.

**Review by robinjhuang — APPROVED** [review]

**Comment by robinjhuang** [comment]
If we copy over the `custom_nodes` directory, we could use the `reinstall` command by passing in a list of custom nodes. @ltdrdata do you have opinion on what would be the best mechanism to "migrate" over custom nodes from another install?

**Comment by robinjhuang** [comment]
@pythongosssss FYI I synced with @ltdrdata and he mentioned he is planning to improve snapshot to also capture python package information. So I think we are good to go with the current approach.

**Review by huchenlei — CHANGES_REQUESTED** [review]
Can you split the global toast change to a separate PR? I feel like having 2 levels of toast now can be confusing. For the custom node migration error reporting, we can fall back to use a electron system level message alert for now, and land the migration part first.

**Review by huchenlei — APPROVED** [review]

**Pull request merged**
